ALTER TABLE destiny_status
ADD COLUMN water INTEGER DEFAULT 1000,
ADD COLUMN max_water INTEGER DEFAULT 1000,
ADD COLUMN food INTEGER DEFAULT 1000,
ADD COLUMN max_food INTEGER DEFAULT 1000,
ADD COLUMN spare_parts INTEGER DEFAULT 100,
ADD COLUMN max_spare_parts INTEGER DEFAULT 100,
ADD COLUMN medical_supplies INTEGER DEFAULT 100,
ADD COLUMN max_medical_supplies INTEGER DEFAULT 100;
