name = 'destiny-backend'
main = 'src/index.ts'
compatibility_date = '2025-05-08'

[[d1_databases]]
binding = 'DB'
database_name = 'stargate-game'
# Fill this in after creating the DB with wrangler d1 create
database_id = '9b6d1e5c-369b-4131-bb9b-076e9abb5f14'
migrations_dir = 'migrations'

# Test environment configuration
[env.test]
d1_databases = [
	{ binding = 'DB', database_name = 'stargate-game-test', database_id = 'test' }
]
