name = 'stargate-evolution-backend'
main = 'src/index.ts'
compatibility_date = '2025-05-08'

[[d1_databases]]
binding = 'DB'
database_name = 'stargate-game'
# Fill this in after creating the DB with wrangler d1 create
database_id = '3a8b2474-999f-4a5f-90fa-e43ef815c0aa'
migrations_dir = 'migrations'

# Test environment configuration
[env.test]
d1_databases = [
	{ binding = 'DB', database_name = 'stargate-game-test', database_id = 'test' }
]

[observability]
enabled = true
